#!/bin/bash

# Controllo se un argomento è stato passato allo script
if [ $# -eq 0 ]; then
    echo "Errore: nessun file specificato."
    echo "Uso: $0 nome_del_file"
    exit 1
fi
# Cambio la directory di lavoro
cd ~/plugin42/plugin

# Salvataggio del nome del file in una variabile
filename="$1"

# Esecuzione del comando python con il modulo c_formatter_42 passando il file come argomento
python3 -m c_formatter_42 "$filename"
hmeah/plugin42/plugin
